const ActivityFlags = ['INSTANCE', 'JOIN', 'SPECTATE', 'JOIN_REQUEST', 'SYNC', 'PLAY'];

const ApplicationFlags = [
	'GATEWAY_PRESENCE',
	'GATEWAY_PRESENCE_LIMITED',
	'GATEWAY_GUILD_MEMBERS',
	'GATEWAY_GUILD_MEMBERS_LIMITED',
	'VERIFICATION_PENDING_GUILD_LIMIT',
	'EMBEDDED',
];

const IntentsFlags = [
	'GUILDS',
	'GUILD_MEMBERS',
	'GUILD_BANS',
	'GUILD_EMOJIS_AND_STICKERS',
	'GUILD_INTEGRATIONS',
	'GUILD_WEBHOOKS',
	'GUILD_INVITES',
	'GUILD_VOICE_STATES',
	'GUILD_PRESENCES',
	'GUILD_MESSAGES',
	'GUILD_MESSAGE_REACTIONS',
	'GUILD_MESSAGE_TYPING',
	'DIRECT_MESSAGES',
	'DIRECT_MESSAGE_REACTIONS',
	'DIRECT_MESSAGE_TYPING',
];

const MessageFlags = [
	'CROSSPOSTED',
	'IS_CROSSPOST',
	'SUPPRESS_EMBEDS',
	'SOURCE_MESSAGE_DELETED',
	'URGENT',
	'HAS_THREAD',
	'EPHEMERAL',
	'LOADING',
];

const PermissionFlags = [
	'CREATE_INSTANT_INVITE',
	'KICK_MEMBERS',
	'BAN_MEMBERS',
	'ADMINISTRATOR',
	'MANAGE_CHANNELS',
	'MANAGE_GUILD',
	'ADD_REACTIONS',
	'VIEW_AUDIT_LOG',
	'PRIORITY_SPEAKER',
	'STREAM',
	'VIEW_CHANNEL',
	'SEND_MESSAGES',
	'SEND_TTS_MESSAGES',
	'MANAGE_MESSAGES',
	'EMBED_LINKS',
	'ATTACH_FILES',
	'READ_MESSAGE_HISTORY',
	'MENTION_EVERYONE',
	'USE_EXTERNAL_EMOJIS',
	'VIEW_GUILD_INSIGHTS',
	'CONNECT',
	'SPEAK',
	'MUTE_MEMBERS',
	'DEAFEN_MEMBERS',
	'MOVE_MEMBERS',
	'USE_VAD',
	'CHANGE_NICKNAME',
	'MANAGE_NICKNAMES',
	'MANAGE_ROLES',
	'MANAGE_WEBHOOKS',
	'MANAGE_EMOJIS_AND_STICKERS',
	'USE_APPLICATION_COMMANDS',
	'REQUEST_TO_SPEAK',
	'MANAGE_THREADS',
	'USE_PUBLIC_THREADS',
	'CREATE_PUBLIC_THREADS',
	'USE_PRIVATE_THREADS',
	'CREATE_PRIVATE_THREADS',
	'USE_EXTERNAL_STICKERS',
	'SEND_MESSAGES_IN_THREADS',
	'START_EMBEDDED_ACTIVITIES',
];

const SystemChannelFlags = [
	'SUPPRESS_JOIN_NOTIFICATIONS',
	'SUPPRESS_PREMIUM_SUBSCRIPTIONS',
	'SUPPRESS_GUILD_REMINDER_NOTIFICATIONS',
];

const UserFlags = [
	'DISCORD_EMPLOYEE',
	'PARTNERED_SERVER_OWNER',
	'HYPESQUAD_EVENTS',
	'BUGHUNTER_LEVEL_1',
	'HOUSE_BRAVERY',
	'HOUSE_BRILLIANCE',
	'HOUSE_BALANCE',
	'EARLY_SUPPORTER',
	'TEAM_USER',
	'BUGHUNTER_LEVEL_2',
	'VERIFIED_BOT',
	'EARLY_VERIFIED_BOT_DEVELOPER',
	'DISCORD_CERTIFIED_MODERATOR',
];

const ChannelTypes = {
	dm: 'DM',
	text: 'GUILD_TEXT',
	voice: 'GUILD_VOICE',
	category: 'GUILD_CATEGORY',
	news: 'GUILDS_NEWS',
	store: 'GUILD_STORE',
	unknown: 'UNKNOWN',
};

module.exports = {
	ActivityFlags,
	ApplicationFlags,
	IntentsFlags,
	MessageFlags,
	PermissionFlags,
	SystemChannelFlags,
	UserFlags,
	ChannelTypes,
};
